---
title: "Carbon Conscious"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Datasets
library(readr)

# Greenhouse gas emissions by country-year, 1750 - 2020
ghg <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2.csv')

# Greenhouse gas emissions by country-year-sector, 1990 - 2018
sectors <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2_sectors.csv')
```

Column {data-width=500}
-----------------------------------------------------------------------

### Present Day Global GHG Emissions

```{r out.width="60%"}
library(ggplot2)
library(dplyr)
library(leaflet)
library(ggthemes)

Present_day <- ghg %>% 
  filter(Entity != "World") %>% 
  filter(Year == 2020) %>% 
  group_by(Entity, `Annual CO2 emissions (zero filled)`) %>% 
  tally() %>% 
  arrange(desc(`Annual CO2 emissions (zero filled)`))

Present_day_CO2_head<- Present_day %>% 
  summarise(total_CO2 = sum(`Annual CO2 emissions (zero filled)`)) %>% 
  mutate(percent = (total_CO2/sum(total_CO2))*100) %>% 
  arrange(desc(percent)) %>% 
  head(15)

Present_day_CO2_tail <- Present_day %>% 
  summarise(total_CO2 = sum(`Annual CO2 emissions (zero filled)`)) %>% 
  mutate(percent = (total_CO2/sum(total_CO2))*100) %>% 
  arrange(desc(percent)) %>% 
  tail(15)

ggplot(data = Present_day_CO2_head, aes( x = Entity, y = percent))+
  geom_col(fill = "deepskyblue")+
  theme(axis.text.x = element_text(angle = 90))+
  labs(title = "2020 Highest CO2 Emitters",
       subtitle = "Top 15",
       y = "Percent CO2 Emissions",
       caption = "Jarely, Tessa, Sam, & Harrison")

ggplot(data = Present_day_CO2_tail, aes( x = Entity, y = percent))+
  geom_col(fill = 'darkmagenta')+
  theme(axis.text.x = element_text(angle = 90))+
  labs(title = "2020 Lowest CO2 Emitters",
       subtitle = "Bottom 15",
       y = "Percent CO2 Emissions",
       caption = "Jarely, Tessa, Sam, & Harrison")
options(scipen = 999)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Carbon Emissions Over Time

```{r out.width="60%"}
#global emissions
globalEmissions <- ghg %>%
  group_by(Year) %>%
  filter(Entity == 'World') %>%
summarise (total = sum(`Annual CO2 emissions (zero filled)`)) %>%
  arrange(desc(total))

ggplot(data = globalEmissions) +
  geom_area(aes(x=Year, y=total/1000000), fill = 'lightblue') +
  labs(x = "Year",
       y = "Emissions/a Million",
       title = "Global CO2 Emissions (in millions",
       subtitle = "From 1750-2020",
       caption = "Jarely, Tessa, Sam, & Harrison")

#sector-by-sector

globalSec <- sectors %>%
  group_by(sector) %>%
  filter(entity == 'World') %>%
summarise (total = sum(`co2`)) %>%
  arrange(desc(total))

ggplot(data = globalSec) +
  geom_col(aes(x = sector, y = total/1000000000, fill = sector)) +
  coord_flip() +
  theme(legend.position = 'NONE') +
  labs(x = "Sectors",
       y = "Total CO2 Emissions",
       title = "Total CO2 Emissions by Sectors (in billions)",
       subtitle = "From 1750-2020",
       caption = "Jarely, Tessa, Sam, & Harrison")

```

### Top 5 Most Emitting Countries

```{r out.width="60%"}

top_5 <- sectors %>% 
  filter(entity != "World") %>% 
  group_by(entity, sector) %>% 
  summarise(total = sum(co2)) %>%
  arrange(desc(total)) %>% 
  head(5)
  
ggplot(data = top_5, aes(x = entity, y = total/1000000000, fill = sector))+
  geom_col(position = 'dodge')+
  theme(axis.text.x = element_text(angle = 90))+
  labs(title = "Top 5 Most Emitting Countries (in Billions)", 
       subtitle = "By Sector", 
       caption = "Jarely, Tessa, Sam, & Harrison",
       y = "total")
```

